// About 页：关于 Catpaq（从设置页挪出，侧栏独立入口）。
// 运行权限（管理员状态）保留在设置页，本页只展示介绍与第三方致谢。
using System.Reflection;
using Microsoft.UI.Xaml;
using Microsoft.UI.Xaml.Controls;
using Catpaq.Core;

namespace Catpaq.Pages;

public sealed partial class AboutPage : Page
{
    private MainWindow Main => App.MainWindow;

    public AboutPage()
    {
        InitializeComponent();
        Loaded += (_, _) =>
        {
            Main.AboutPage = this;
            ApplyLanguage();
        };
    }

    public void ApplyLanguage()
    {
        LblTitle.Text = Main.T("about.title", "About Catpaq");
        var version = Assembly.GetExecutingAssembly().GetName().Version?.ToString(3) ?? "?";
        var zh = Main.LangName.StartsWith("zh");
        var sb = new System.Text.StringBuilder();
        sb.AppendLine($"Catpaq {version} (WinUI 3)");
        sb.AppendLine();
        sb.AppendLine(Main.T("about.desc", "ZPAQ archive manager built on the zpaqfranz engine."));
        sb.AppendLine();
        sb.Append(Main.T("about.repo", "Repository: "));
        sb.AppendLine("https://github.com/239484654/catpaq_winUI3");
        sb.AppendLine();
        sb.AppendLine(Main.T("about.third", "Third-party acknowledgements:"));
        if (zh)
        {
            sb.AppendLine("• catpaq —— 原始 Lazarus 项目（https://github.com/fcorbelli/catpaq）");
            sb.AppendLine("• Microsoft Windows App SDK / WinUI 3");
            sb.AppendLine("• .NET 10");
            sb.AppendLine("• zpaqfranz（https://zpaqfranz.com）");
            sb.AppendLine("• Files Community —— 侧边栏、地址栏（Omnibar 与 BreadcrumbBar）移植自 Files");
            sb.AppendLine("  （MIT License，https://github.com/files-community/Files）");
            sb.AppendLine();
            sb.AppendLine("本软件的部分代码与界面翻译由 DeepSeek AI 生成。");
            sb.AppendLine("如有问题还望见谅。");
            sb.AppendLine();
            sb.AppendLine("本软件采用 MIT 协议授权；一切以 MIT 协议为准，许可协议原文如下（不可翻译）：");
            sb.AppendLine();
            sb.AppendLine(I18n.MitLicense);
        }
        else
        {
            sb.AppendLine("• catpaq — original Lazarus project (https://github.com/fcorbelli/catpaq)");
            sb.AppendLine("• Microsoft Windows App SDK / WinUI 3");
            sb.AppendLine("• .NET 10");
            sb.AppendLine("• zpaqfranz (https://zpaqfranz.com)");
            sb.AppendLine("• Files Community — sidebar & address bar (Omnibar & BreadcrumbBar) ported from Files");
            sb.AppendLine("  (MIT License, https://github.com/files-community/Files)");
            sb.AppendLine();
            sb.AppendLine("Parts of this software's code and UI translations were generated by DeepSeek AI.");
            sb.AppendLine("We apologize for any issues.");
            sb.AppendLine();
            sb.AppendLine("This software is licensed under the MIT License; in all cases, the MIT License shall prevail. The license text is shown below (must not be translated):");
            sb.AppendLine();
            sb.AppendLine(I18n.MitLicense);
        }
        LblBody.Text = sb.ToString().TrimEnd();
    }
}
